---
Name: databasebackup_config
Before: 'mysite/*'
After: 'framework/*','cms/*'
---

DatabasebackupLog:
  compression: ''


Director:
  rules:
    'backupsystem//$Action/$ID/$OtherID': 'DatabasebackupLogDetailForm_Controller'
